<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-226bd0f977fa82dfae4534cac220d79a.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.23">

  <meta name="author" content="Tobias Vlćek">
  <title>Materiallogistik – Vorlesung 05: Bestandsentscheidungen bei Unsicherheit</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2d5f2325800fef3a049173b76a24a0f0.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Vorlesung 05: Bestandsentscheidungen bei Unsicherheit</h1>
  <p class="subtitle">Vom Zeitungsverkäufer zum smarten Lagermanagement</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Tobias Vlćek 
</div>
</div>
</div>

</section>
<section id="das-grundsetting" class="slide level2">
<h2>1. Das Grundsetting</h2>
<p>Nehmen wir an, wir leiten eine kleine Brauerei.</p>
<ul>
<li>Jedes Jahr zu Weihnachten brauen wir ein ganz besonderes, limitiertes Festbier. Die Nachfrage ist riesig, aber auch ungewiss.</li>
<li>Wenn wir zu viel brauen, bleiben wir auf den Flaschen sitzen und machen Verlust.</li>
<li>Brauen wir zu wenig, sind unsere treuen Kunden enttäuscht, und uns entgeht ein Gewinn.</li>
<li>Dies ist eine <strong>einmalige Entscheidung</strong>.</li>
</ul>
<p>Ganz anders sieht es bei unserem Standard-Pils aus.</p>
<ul>
<li>Es wird das ganze Jahr über verkauft.</li>
<li>Hier müssen wir nicht einmal, sondern <strong>laufend</strong> entscheiden: Wann bestellen wir neuen Hopfen und Malz, und wie viel davon?</li>
<li>Das ist eine <strong>mehrperiodige Entscheidung</strong>.</li>
</ul>
<p>Beides schauen wir uns nun genauer an.</p>
</section>
<section id="das-newsvendor-problem" class="slide level2 scrollable">
<h2>2. Das Newsvendor-Problem</h2>
<p>Das “Zeitungsverkäufer-Problem” (Newsvendor Problem) ist der Klassiker für einmalige Bestandsentscheidungen. Der Name kommt von einem Zeitungsjungen, der morgens entscheiden muss, wie viele Zeitungen er kauft, ohne die genaue Nachfrage des Tages zu kennen. Abends sind die übrigen Zeitungen wertlos.</p>
<p>Dieses Prinzip gilt für viele Produkte:</p>
<ul>
<li>Saisonale Modeartikel</li>
<li>Tickets für ein Konzert oder Sportereignis</li>
<li>Der Tannenbaumverkauf vor Weihnachten</li>
<li><strong>Unser limitiertes Festbier</strong></li>
</ul>
<p>Im Kern geht es immer um die Abwägung zweier Risiken:</p>
<ul>
<li><strong>Overage-Kosten (<span class="math inline">\(c_O\)</span>):</strong> Die Kosten für jede Einheit, die wir <strong>zu viel</strong> bestellt haben und die am Ende übrig bleibt.</li>
<li><strong>Underage-Kosten (<span class="math inline">\(c_U\)</span>):</strong> Die Kosten für jede nachgefragte Einheit, die wir <strong>zu wenig</strong> bestellt haben (entgangener Gewinn).</li>
</ul>
<p><strong>Beispiel: Unser Festbier</strong></p>
<ul>
<li><strong>Herstellungskosten pro Flasche:</strong> 3 GE</li>
<li><strong>Verkaufspreis pro Flasche:</strong> 8 GE</li>
<li><strong>Restwert:</strong> Nicht verkaufte Flaschen können wir für 1 GE pro Stück an einen Restposten-Händler verkaufen.</li>
</ul>
<p>Daraus berechnen wir die Kosten:</p>
<ul>
<li><strong>Underage-Kosten (<span class="math inline">\(c_U\)</span>):</strong> Wenn uns eine Flasche zur Bedienung der Nachfrage fehlt, entgeht uns der Gewinn. <span class="math display">\[c_U = \text{Verkaufspreis} - \text{Herstellungskosten} = 8 - 3 = 5 \text{ GE}\]</span></li>
<li><strong>Overage-Kosten (<span class="math inline">\(c_O\)</span>):</strong> Jede Flasche, die wir zu viel produzieren, verursacht einen Verlust. <span class="math display">\[c_O = \text{Herstellungskosten} - \text{Restwert} = 3 - 1 = 2 \text{ GE}\]</span></li>
</ul>
<h3 id="das-kritische-verhältnis-critical-ratio">Das kritische Verhältnis (Critical Ratio)</h3>
<p>Wir suchen die optimale Bestellmenge, die den erwarteten Gewinn maximiert.</p>
<ul>
<li>Die Lösung liegt im <strong>kritischen Verhältnis</strong>, auch “Critical Ratio” genannt.</li>
<li>Es gibt uns den optimalen Servicegrad vor, bei dem der <strong>erwartete Gewinn maximiert wird</strong>.</li>
</ul>
<p><strong>Die Logik:</strong></p>
<ul>
<li>Wir sollten so lange eine zusätzliche Einheit auf Lager nehmen, wie der erwartete Gewinn aus dem Verkauf dieser Einheit größer ist als der erwartete Verlust, falls wir sie nicht verkaufen.</li>
<li><span class="math inline">\(c_U \cdot P(\text{Nachfrage} \ge x)\)</span> ist der erwartete Gewinn aus dem Verkauf dieser Einheit.</li>
<li><span class="math inline">\(c_O \cdot P(\text{Nachfrage} &lt; x)\)</span> ist der erwartete Verlust, falls wir sie nicht verkaufen.</li>
<li><strong>Das kritische Verhältnis ist der Punkt, an dem sich diese beiden die Waage halten.</strong></li>
</ul>
<p><span class="math display">\[
\text{Kritisches Verhältnis} = F(x_{opt}) = \frac{c_U}{c_O + c_U}
\]</span></p>
<p>Für unser Festbier bedeutet das:</p>
<p><span class="math display">\[
\text{Kritisches Verhältnis} = \frac{5}{2 + 5} = \frac{5}{7} \approx 0.714
\]</span></p>
<p>Das bedeutet: Wir sollten so viele Flaschen brauen, dass die Wahrscheinlichkeit, die gesamte Nachfrage zu decken, bei ca. 71,4% liegt.</p>
<h3 id="die-optimale-bestellmenge-finden">Die optimale Bestellmenge finden</h3>
<p>Jetzt, da wir das Ziel kennen (71,4% Servicegrad), müssen wir nur noch die passende Bestellmenge finden. Wie wir das tun, hängt von der Art der Nachfrageverteilung ab.</p>
<h4 id="fall-1-diskrete-nachfrage">Fall 1: Diskrete Nachfrage</h4>
<p>Stellen wir uns einen Food-Truck vor, der an einem einzigen Tag auf einem Festival ein spezielles, teures Gericht anbietet.</p>
<ul>
<li>Die Herstellungskosten liegen bei 8 GE.</li>
<li>Der Verkaufspreis beträgt 20 GE.</li>
<li>Reste sind wertlos (<span class="math inline">\(c_O = 8, c_U = 12\)</span>).</li>
<li>Das kritische Verhältnis ist <span class="math inline">\(12 / (8 + 12) = 0.6\)</span>.</li>
</ul>
<p>Die Erfahrung zeigt folgende Nachfrageverteilung:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Nachfrage (x)</th>
<th style="text-align: center;">P(x)</th>
<th style="text-align: center;">Kumulierte P(Y&lt;=x)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">10 Gerichte</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">11 Gerichte</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12 Gerichte</td>
<td style="text-align: center;">0.30</td>
<td style="text-align: center;"><strong>0.75</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">13 Gerichte</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">0.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14 Gerichte</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">1.00</td>
</tr>
</tbody>
</table>
<p><strong>Regel:</strong></p>
<p>Wir suchen die <strong>kleinste Bestellmenge x</strong>, für die die kumulierte Wahrscheinlichkeit <span class="math inline">\(F(x) = P(Y \le x)\)</span> <strong>größer oder gleich</strong> dem kritischen Verhältnis ist.</p>
<ul>
<li><span class="math inline">\(F(10) = 0.20 &lt; 0.6\)</span></li>
<li><span class="math inline">\(F(11) = 0.45 &lt; 0.6\)</span></li>
<li><span class="math inline">\(F(12) = 0.75 \ge 0.6\)</span> –&gt; <strong>STOPP!</strong></li>
</ul>
<p>Die optimale Bestellmenge ist <strong>12 Gerichte</strong>. Obwohl die Wahrscheinlichkeit für 12 verkaufte Gerichte nur bei 30% liegt, ist das die beste Entscheidung, um den erwarteten Gewinn zu maximieren.</p>
<h4 id="fall-2-stetige-normalverteilte-nachfrage">Fall 2: Stetige (Normalverteilte) Nachfrage</h4>
<p>Zurück zu unserem Beispiel mit dem Festbier unserer Brauerei.</p>
<ul>
<li>Bei Tausenden von Kunden ist die Nachfrage eher eine stetige, glockenförmige Kurve.</li>
<li>Nehmen wir an, die Nachfrage ist <strong>normalverteilt</strong>.</li>
<li>Wir haben einen Erwartungswert von <span class="math inline">\(\mu=2000\)</span> Flaschen.</li>
<li>Ferner schätzen wir eine Standardabweichung von <span class="math inline">\(\sigma=300\)</span> Flaschen.</li>
</ul>
<p>Hier nutzen wir die Formel:</p>
<p><span class="math display">\[
x_{opt} = \mu + z \cdot \sigma
\]</span></p>
<ul>
<li>Der <strong>Sicherheitsfaktor z</strong> ist die Brücke zwischen unserem kritischen Verhältnis und der Bestellmenge.</li>
<li>Wir finden ihn, indem wir die <strong>inverse Standardnormalverteilung</strong> für unser kritisches Verhältnis von 0.714 berechnen. Je höher der angestrebte Servicegrad (das kritische Verhältnis), desto überproportional größer wird der notwendige Sicherheitsfaktor.</li>
</ul>
<p><strong>Z-Werte für gängige Servicegrade (Kritisches Verhältnis)</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 11%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(\alpha\)</span>-Servicegrad</th>
<th style="text-align: center;">z-Wert</th>
<th style="text-align: left;">Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">50%</td>
<td style="text-align: center;">0.000</td>
<td style="text-align: left;">Exakt der Erwartungswert (kein Puffer).</td>
</tr>
<tr class="even">
<td style="text-align: left;">55%</td>
<td style="text-align: center;">0.126</td>
<td style="text-align: left;">0.126 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">60%</td>
<td style="text-align: center;">0.253</td>
<td style="text-align: left;">0.253 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">65%</td>
<td style="text-align: center;">0.385</td>
<td style="text-align: left;">0.385 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">70%</td>
<td style="text-align: center;">0.524</td>
<td style="text-align: left;">0.524 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">75%</td>
<td style="text-align: center;">0.674</td>
<td style="text-align: left;">0.674 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80%</td>
<td style="text-align: center;">0.842</td>
<td style="text-align: left;">0.842 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">85%</td>
<td style="text-align: center;">1.036</td>
<td style="text-align: left;">1.036 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">90%</td>
<td style="text-align: center;">1.282</td>
<td style="text-align: left;">1.282 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">95%</td>
<td style="text-align: center;">1.645</td>
<td style="text-align: left;">1.645 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">99%</td>
<td style="text-align: center;">2.326</td>
<td style="text-align: left;">2.326 Standardabweichungen als Puffer.</td>
</tr>
</tbody>
</table>
<p>Wir gehen wie folgt vor:</p>
<ol type="1">
<li><strong>z-Wert finden:</strong> <span class="math inline">\(\Phi(z) = 0.714 \implies z \approx 0.565\)</span> <sup>1</sup></li>
<li><strong>Optimale Menge berechnen:</strong> <span class="math inline">\(x_{opt} = 2000 + 0.565 \cdot 300 \approx 2000 + 170 = 2170\)</span> Flaschen.</li>
<li><strong>Sicherheitsbestand:</strong> Der Teil über dem Erwartungswert ist unser Puffer gegen Unsicherheit. Sicherheitsbestand = <span class="math inline">\(x_{opt} - \mu = 2170 - 2000 = 170\)</span> Flaschen.</li>
</ol>
<p>Wir sollten also 2170 Flaschen brauen, um unseren erwarteten Gewinn zu maximieren.</p>
<aside><ol class="aside-footnotes"><li id="fn1"><p>Mit Excel <code>NORM.S.INV(0.714)</code>, Python <code>norm.ppf(0.714)</code> oder aus einer Tabelle ablesen.</p></li></ol></aside></section>
<section id="die-s-q-politik-mit-undershoot" class="slide level2 scrollable">
<h2>3. Die (s, q)-Politik mit Undershoot</h2>
<p>Für Produkte, die wir kontinuierlich führen, brauchen wir eine laufende Strategie. Hier ist die <strong>(s, q)-Politik</strong>, die wir bereits in der letzten Vorlesung kennengelernt haben, eine oft verwendete Strategie.</p>
<p>Zur Erinnerung:</p>
<ul>
<li>Wir überwachen den Lagerbestand <strong>kontinuierlich</strong>.</li>
<li>Fällt der <em>disponible Bestand</em> auf oder unter den <strong>Bestellpunkt (s)</strong>, lösen wir eine Bestellung aus.</li>
<li>Die <strong>Bestellmenge (q)</strong> ist immer fest.</li>
</ul>
<p>Ein Problem dabei ist das “Unterschießen” des Bestellpunkts, der sogenannte <strong>Undershoot</strong>. Wenn wir den Bestand nur täglich prüfen, kann eine große Nachfrage den Bestand weit unter <code>s</code> drücken, bevor wir überhaupt bestellen. Dieser Undershoot (<span class="math inline">\(U\)</span>) ist eine zusätzliche Zufallsgröße, die wir berücksichtigen müssen.</p>
<p>Für eine normalverteilte Tagesnachfrage <span class="math inline">\(D \sim N(\mu_D, \sigma_D^2)\)</span> können wir den Undershoot so abschätzen:</p>
<ul>
<li><strong>Erwarteter Undershoot:</strong> <span class="math inline">\(E\{U\} \approx \frac{\sigma_D^2 + \mu_D^2}{2 \mu_D}\)</span></li>
<li><strong>Varianz des Undershoots:</strong> <span class="math inline">\(\operatorname{Var}\{U\} \approx \frac{\sigma_D^2}{2} \left(1 - \frac{\sigma_D^2}{2\mu_D^2}\right) + \frac{\mu_D^2}{12}\)</span></li>
</ul>
<h3 id="den-bestellpunkt-s-bestimmen">Den Bestellpunkt <code>s</code> bestimmen</h3>
<p>Der <strong>Risikozeitraum</strong> ist die Wiederbeschaffungszeit <span class="math inline">\(L\)</span>. Die Nachfrage <span class="math inline">\(Y\)</span>, die unser Bestellpunkt abdecken muss, ist die Summe aus der Nachfrage während der WBZ (<span class="math inline">\(Y^{(L)}\)</span>) und dem Undershoot (<span class="math inline">\(U\)</span>).</p>
<ul>
<li>Erwartungswert: <span class="math inline">\(\mu_Y = \mu_L + E\{U\} = (L \cdot \mu_D) + E\{U\}\)</span></li>
<li>Varianz: <span class="math inline">\(\sigma_Y^2 = \sigma_L^2 + \operatorname{Var}\{U\} = (L \cdot \sigma_D^2) + \operatorname{Var}\{U\}\)</span></li>
</ul>
<p>Um den optimalen Bestellpunkt <span class="math inline">\(s_{opt}\)</span> für einen angestrebten <strong><span class="math inline">\(\beta\)</span>-Servicegrad</strong> (Fill Rate) zu finden, nutzen wir wieder eine Formel, die auf der Einheiten-Verlustfunktion <span class="math inline">\(G_Z^{(1)}(v)\)</span> basiert.</p>
<p><strong>Zielbedingung:</strong> Finde den kleinsten Sicherheitsfaktor <span class="math inline">\(v\)</span>, für den gilt: <span class="math display">\[
G_Z^{(1)}(v) \leq \frac{(1-\beta) \cdot q}{\sigma_Y}
\]</span> Der optimale Bestellpunkt ist dann: <span class="math inline">\(s_{opt} = \mu_Y + v_{opt} \cdot \sigma_Y\)</span>.</p>
<p>Den Wert für <span class="math inline">\(v_{opt}\)</span> findet man, indem man den Zielwert für die Verlustfunktion in einer Tabelle nachschlägt oder einfach in einer Software berechnet.</p>
<p><strong>Tabelle der Standard-Verlustfunktion <span class="math inline">\(G_Z^{(1)}(v)\)</span></strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">v</th>
<th style="text-align: center;"><span class="math inline">\(G_Z^{(1)}(v)\)</span></th>
<th style="text-align: center;">v</th>
<th style="text-align: center;"><span class="math inline">\(G_Z^{(1)}(v)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.399</td>
<td style="text-align: center;">1.1</td>
<td style="text-align: center;">0.069</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0.359</td>
<td style="text-align: center;">1.2</td>
<td style="text-align: center;">0.056</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">0.323</td>
<td style="text-align: center;"><strong>1.25</strong></td>
<td style="text-align: center;"><strong>0.051</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.3</td>
<td style="text-align: center;">0.291</td>
<td style="text-align: center;">1.3</td>
<td style="text-align: center;">0.046</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.4</td>
<td style="text-align: center;">0.262</td>
<td style="text-align: center;">1.4</td>
<td style="text-align: center;">0.038</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.235</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">0.031</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.6</td>
<td style="text-align: center;">0.211</td>
<td style="text-align: center;">1.6</td>
<td style="text-align: center;">0.026</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">0.189</td>
<td style="text-align: center;">1.7</td>
<td style="text-align: center;">0.021</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.8</td>
<td style="text-align: center;">0.169</td>
<td style="text-align: center;">1.8</td>
<td style="text-align: center;">0.017</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0.148</td>
<td style="text-align: center;">1.9</td>
<td style="text-align: center;">0.014</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">0.083</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">0.011</td>
</tr>
</tbody>
</table>
<p><strong>Beispiel:</strong></p>
<ul>
<li>Ein Bauteil hat eine tägliche Nachfrage von <span class="math inline">\(\mu_D=20, \sigma_D=5\)</span>.</li>
<li>Die WBZ ist <span class="math inline">\(L=10\)</span> Tage, die feste Bestellmenge <span class="math inline">\(q=300\)</span>.</li>
<li>Wir streben <span class="math inline">\(\beta=97\%\)</span> an.</li>
</ul>
<ol type="1">
<li><strong>Undershoot berechnen:</strong> <span class="math inline">\(E\{U\} \approx (5^2 + 20^2) / (2 \cdot 20) = 10.625\)</span> <span class="math inline">\(\operatorname{Var}\{U\} \approx 5^2/2 \cdot (1 - 5^2/(2 \cdot 20^2)) + 20^2/12 \approx 45.42\)</span></li>
<li><strong>Nachfrage im Risikozeitraum:</strong> <span class="math inline">\(\mu_Y = (10 \cdot 20) + 10.625 = 210.625\)</span> <span class="math inline">\(\sigma_Y^2 = (10 \cdot 5^2) + 45.42 = 295.42 \implies \sigma_Y \approx 17.19\)</span></li>
<li><strong>Zielwert für Verlustfunktion:</strong> Target <span class="math inline">\(G_Z^{(1)}(v) = (1 - 0.97) \cdot 300 / 17.19 \approx 0.523\)</span></li>
<li><strong><span class="math inline">\(v_{opt}\)</span> finden:</strong>
<ul>
<li>Wir suchen <code>v</code>, sodass <span class="math inline">\(G_Z^{(1)}(v) \le 0.523\)</span>. Dies geschieht durch Nachschlagen in einer Tabelle der Standard-Verlustfunktion oder mittels Software.</li>
<li>Die Funktion <span class="math inline">\(G_Z^{(1)}(v)\)</span> hat für <span class="math inline">\(v=0\)</span> einen Wert von ca. 0.399. Für alle <span class="math inline">\(v&gt;0\)</span> ist der Funktionswert kleiner.</li>
<li>Da unser Zielwert von <span class="math inline">\(0.523\)</span> größer ist als <span class="math inline">\(0.399\)</span>, ist die Bedingung bereits für <span class="math inline">\(v=0\)</span> erfüllt.</li>
<li>In der Praxis wird in diesem Fall der Sicherheitsfaktor auf 0 gesetzt, da kein positiver Puffer benötigt wird.</li>
<li>Daher: <span class="math inline">\(v_{opt} \approx 0.0\)</span>.</li>
</ul></li>
<li><strong>Bestellpunkt <span class="math inline">\(s_{opt}\)</span>:</strong> <span class="math inline">\(s_{opt} = 210.625 + 0.0 \cdot 17.19 \approx 211\)</span> Stück. Der Bestellpunkt sollte auf 211 Stück gesetzt werden.</li>
</ol>
</section>
<section id="die-periodische-politik-r-s" class="slide level2 scrollable">
<h2>4. Die periodische Politik (r, S)</h2>
<p>Nicht für jedes Produkt lohnt sich eine ständige Überwachung. Für Joghurt im Supermarkt ist es effizienter, nur einmal pro Woche (periodisch) nachzusehen und aufzufüllen. Hierfür eignet sich die <strong>(r, S)-Politik</strong>.</p>
<ul>
<li>Wir prüfen den Bestand nur in festen Intervallen, z.B. alle <strong>r=7 Tage</strong>.</li>
<li>Wir bestellen dann eine variable Menge, um den Bestand auf ein festes <strong>Bestellniveau (S)</strong> aufzufüllen.</li>
</ul>
<h3 id="der-längere-risikozeitraum-r-l">Der längere Risikozeitraum: r + L</h3>
<p>Hier müssen wir umdenken: Der <strong>Risikozeitraum ist jetzt <span class="math inline">\(r+L\)</span></strong>! Warum? Eine Bestellung, die wir heute aufgeben, muss die Nachfrage so lange decken, bis die <em>nächste</em> Lieferung eintrifft. Die nächste Bestellung lösen wir erst in <span class="math inline">\(r\)</span> Tagen aus, und diese braucht dann nochmal <span class="math inline">\(L\)</span> Tage, um anzukommen.</p>
<ul>
<li>Nachfrage im Risikozeitraum: <span class="math inline">\(\mu_{r+L} = (r+L) \cdot \mu_d\)</span></li>
<li>Standardabweichung: <span class="math inline">\(\sigma_{r+L} = \sqrt{r+L} \cdot \sigma_d\)</span></li>
</ul>
<h3 id="das-bestellniveau-s-bestimmen">Das Bestellniveau <code>S</code> bestimmen</h3>
<p>Auch hier können wir das optimale Bestellniveau <span class="math inline">\(S_{opt}\)</span> für einen Ziel-<strong><span class="math inline">\(\beta\)</span>-Servicegrad</strong> bestimmen. Die Logik ist sehr ähnlich zur (s,q)-Politik, aber die Formel für die Zielbedingung ist leicht anders, da die erwartete Fehlmenge ins Verhältnis zur erwarteten Nachfrage im Bestellintervall (<span class="math inline">\(r \cdot \mu_d\)</span>) gesetzt wird.</p>
<p><strong>Zielbedingung (vereinfacht):</strong><sup>1</sup> Finde den kleinsten Sicherheitsfaktor <span class="math inline">\(v\)</span>, für den gilt: <span class="math display">\[
G_Z^{(1)}(v) \leq \frac{(1-\beta) \cdot r \cdot \mu_d}{\sigma_{r+L}}
\]</span> Das optimale Bestellniveau ist dann: <span class="math inline">\(S_{opt} = \mu_{r+L} + v_{opt} \cdot \sigma_{r+L}\)</span>.</p>
<p><strong>Beispiel:</strong> Ein Supermarkt verkauft Frischmilch.</p>
<ul>
<li>Bestand wird alle <strong>r=3 Tage</strong> geprüft.</li>
<li>Die Lieferzeit beträgt <strong>L=1 Tag</strong>.</li>
<li>Tägliche Nachfrage: <span class="math inline">\(\mu_d=50\)</span> Packungen, <span class="math inline">\(\sigma_d=15\)</span>.</li>
<li>Angestrebter Servicegrad: <span class="math inline">\(\beta=99\%\)</span>.</li>
</ul>
<ol type="1">
<li><strong>Risikozeitraum:</strong> <span class="math inline">\(r+L = 3 + 1 = 4\)</span> Tage.</li>
<li><strong>Nachfrage im Risikozeitraum:</strong> <span class="math inline">\(\mu_{r+L} = 4 \cdot 50 = 200\)</span> <span class="math inline">\(\sigma_{r+L} = \sqrt{4} \cdot 15 = 30\)</span></li>
<li><strong>Zielwert für Verlustfunktion:</strong> Target <span class="math inline">\(G_Z^{(1)}(v) = (1-0.99) \cdot 3 \cdot 50 / 30 = 0.05\)</span></li>
<li><strong><span class="math inline">\(v_{opt}\)</span> finden:</strong>
<ul>
<li>Wir suchen den <code>v</code>-Wert, für den <span class="math inline">\(G_Z^{(1)}(v) \leq 0.05\)</span> ist.</li>
</ul></li>
<li><strong>Bestellniveau <span class="math inline">\(S_{opt}\)</span>:</strong> <span class="math inline">\(S_{opt} = 200 + 1.25 \cdot 30 = 237.5 \approx 238\)</span> Packungen. Jeden dritten Tag wird so viel Milch bestellt, dass der verfügbare Bestand wieder auf 238 Packungen ansteigt.</li>
</ol>
<aside><ol class="aside-footnotes"><li id="fn2"><p>Die Formel ist exakt unter der Annahme, dass die durchschnittliche Bestellmenge genau <span class="math inline">\(r \cdot \mu_d\)</span> ist. In einem System mit Fehlbeständen (Backorders) ist die durchschnittliche Bestellmenge jedoch leicht höher als die durchschnittliche Nachfrage, da in Zyklen nach einem Fehlbestand nicht nur die Nachfrage der aktuellen Periode, sondern auch der aufgestaute Fehlbestand aus der Vorperiode bedient werden muss.</p></li></ol></aside></section>
<section id="welche-politik-für-welches-problem" class="slide level2">
<h2>5. Welche Politik für welches Problem?</h2>
<ul>
<li><strong>Newsvendor-Modell:</strong> Perfekt für <strong>einmalige Bestellentscheidungen</strong> bei saisonalen oder verderblichen Produkten. Es balanciert elegant die Kosten von “zu viel” und “zu wenig”.</li>
<li><strong>(s, q)-Politik:</strong> Ideal für <strong>wichtige oder teure Produkte</strong>, bei denen sich eine <strong>kontinuierliche Überwachung</strong> lohnt. Sie arbeitet mit einem festen Sicherheitsbestand und einer festen Bestellmenge.</li>
<li><strong>(r, S)-Politik:</strong> Die richtige Wahl für <strong>Standardprodukte</strong> mit geringerem Wert, bei denen eine <strong>periodische Überprüfung</strong> ausreicht. Sie ist einfacher zu handhaben, erfordert aber einen höheren Sicherheitsbestand, da der Risikozeitraum länger ist.</li>
</ul>


</section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Vorlesung 05: Bestandsentscheidungen bei Unsicherheit | Tobias Vlćek | <a href="../part-05/mlb-lecture-05_new.html">Home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1200,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/beyondsimulations\.github\.io\/Materiallogistik");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>