<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-226bd0f977fa82dfae4534cac220d79a.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.23">

  <meta name="author" content="Tobias Vlćek">
  <title>Materiallogistik – Vorlesung 04: Bestandsmanagement</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2d5f2325800fef3a049173b76a24a0f0.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#025259" class="quarto-title-block center">
  <h1 class="title">Vorlesung 04: Bestandsmanagement</h1>
  <p class="subtitle">Wann bestellen und wie viel auf Lager halten bei ungewisser Nachfrage?</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Tobias Vlćek 
</div>
</div>
</div>

</section>
<section id="ungewisse-nachfrage" class="slide level2">
<h2>1. Ungewisse Nachfrage</h2>
<p>Stellen wir uns vor, wir betreiben einen Online-Shop für ein beliebtes Produkt, zum Beispiel hochwertige Kaffeebohnen. Jeden Tag bestellen Kunden bei uns, aber wir wissen nie genau, wie viele es sein werden. Mal sind es 10 Beutel, mal 30.</p>
<p>Das bringt uns in ein klassisches Dilemma:</p>
<ul>
<li><strong>Zu viel auf Lager?</strong> Wir binden Kapital, das wir anderswo nutzen könnten, und riskieren, dass die Bohnen an Aroma verlieren. Das sind <strong>Lagerhaltungskosten</strong>.</li>
<li><strong>Zu wenig auf Lager?</strong> Kunden wollen bestellen, aber das Produkt ist ausverkauft. Wir sind unzufrieden, gehen zur Konkurrenz und kommen vielleicht nie wieder. Das sind <strong>Fehlmengenkosten</strong>.</li>
</ul>
<p>Im Gegensatz zu den bisherigen Vorlesungen, haben wir dieses mal eine ungewisse Nachfrage! Die zwei zentralen Fragen sind:</p>
<ul>
<li><strong>Wann</strong> sollen wir eine neue Lieferung bei unserem Kaffeeröster bestellen?</li>
<li><strong>Wie viel</strong> sollen wir dann bestellen?</li>
</ul>
</section>
<section id="kennzahlen-im-lager" class="slide level2 scrollable">
<h2>2. Kennzahlen im Lager</h2>
<p>Um unser Lager gut zu steuern, müssen wir die Bestände präzise erfassen. Es gibt verschiedene Arten von Beständen, die wir unterscheiden müssen.</p>
<ul>
<li><strong>Physischer Bestand (<span class="math inline">\(I^P\)</span>):</strong> Das ist die Menge, die wir tatsächlich in unserem Regal zählen können.</li>
<li><strong>Bestellbestand (<span class="math inline">\(I^O\)</span>):</strong> Das ist die Menge, die wir bereits bestellt haben, die aber noch nicht geliefert wurde. Man nennt dies auch “offene Bestellungen”.</li>
<li><strong>Fehlbestand (<span class="math inline">\(I^B\)</span>):</strong> Die Menge, die von Kunden nachgefragt wurde, die wir aber nicht liefern konnten, weil unser Lager leer war. Diese Kunden warten noch auf ihre Lieferung.</li>
</ul>
<p>Die wichtigste Kennzahl für unsere Bestellentscheidung ist der <strong>Disponibler Bestand (<span class="math inline">\(I^D\)</span>)</strong>, auch “Bestandsposition” genannt. Er gibt an, wie viel Ware uns <em>insgesamt</em> zur Verfügung steht, um zukünftige Nachfragen zu decken.</p>
<p><span class="math display">\[
I^D = \text{Physischer Bestand} + \text{Bestellbestand} - \text{Fehlbestand}
\]</span> <span class="math display">\[
I^D = I^P + I^O - I^B
\]</span></p>
<p>Warum ist diese Zahl so wichtig? Weil sie die <em>gesamte</em> Versorgungslage berücksichtigt. Eine Bestellung auszulösen, nur weil der physische Bestand niedrig ist, wäre ein Fehler, wenn bereits eine große Lieferung unterwegs ist.</p>
<h3 id="beispiel-eine-woche-im-lager">Beispiel: Eine Woche im Lager</h3>
<p>Schauen wir uns an, wie sich diese Zahlen im Zeitverlauf ändern. Wir verwenden eine <strong>(s, q)-Politik</strong>.</p>
<ul>
<li><strong>Bestellpunkt (s):</strong> Wenn der <em>disponible Bestand</em> auf <strong>s</strong> oder darunter fällt, wird eine neue Bestellung ausgelöst.</li>
<li><strong>Bestellmenge (q):</strong> Es wird immer eine feste Menge von <strong>q</strong> Stück bestellt.</li>
<li><strong>Wiederbeschaffungszeit (L):</strong> Es dauert <strong>L</strong> Zeiteinheiten (z.B. Wochen), bis eine Bestellung ankommt.</li>
</ul>
<p><strong>Szenario:</strong></p>
<ul>
<li><span class="math inline">\(s=100\)</span>, <span class="math inline">\(q=250\)</span>, <span class="math inline">\(L=3\)</span> Wochen.</li>
<li>Start in Woche 0 mit <span class="math inline">\(I^P_0 = 120\)</span>, <span class="math inline">\(I^O_0 = 0\)</span>, <span class="math inline">\(I^B_0 = 0\)</span>.</li>
<li>Daraus folgt: <span class="math inline">\(I^D_0 = 120 + 0 - 0 = 120\)</span>.</li>
</ul>
<p><strong>Ablauf innerhalb einer Woche:</strong></p>
<ol type="1">
<li><strong>Wareneingang:</strong> Zu Beginn der Woche treffen eventuell alte Bestellungen ein.</li>
<li><strong>Nachfrage:</strong> Kunden bestellen, was den Bestand reduziert.</li>
<li><strong>Bestellentscheidung:</strong> Am Ende der Woche prüfen wir den disponiblen Bestand und bestellen bei Bedarf.</li>
</ol>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Woche</th>
<th style="text-align: left;">Ereignisse</th>
<th style="text-align: center;"><span class="math inline">\(d_t\)</span></th>
<th style="text-align: center;"><span class="math inline">\(I^P\)</span></th>
<th style="text-align: center;"><span class="math inline">\(I^O\)</span></th>
<th style="text-align: center;"><span class="math inline">\(I^B\)</span></th>
<th style="text-align: center;"><span class="math inline">\(I^D\)</span></th>
<th style="text-align: left;">Kommentar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>0</strong></td>
<td style="text-align: left;"><strong>Start</strong></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><strong>120</strong></td>
<td style="text-align: left;">Anfangszustand. <span class="math inline">\(I^D &gt; s\)</span>, keine Bestellung.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: left;">Nachfrage</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><strong>90</strong></td>
<td style="text-align: left;"><span class="math inline">\(I^P\)</span> sinkt. <span class="math inline">\(I^D = 120 - 30 = 90\)</span>. <span class="math inline">\(I^D &lt; s\)</span>, also Bestellung!</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: left;"><strong>Bestellung</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><strong>340</strong></td>
<td style="text-align: left;">Bestellung über 250 Stück wird ausgelöst. <span class="math inline">\(I^O\)</span> steigt. <span class="math inline">\(I^D\)</span> steigt <em>sofort</em> um 250.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: left;">Nachfrage</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><strong>300</strong></td>
<td style="text-align: left;"><span class="math inline">\(I^P\)</span> sinkt. <span class="math inline">\(I^D = 340 - 40 = 300\)</span>. <span class="math inline">\(I^D &gt; s\)</span>, keine neue Bestellung.</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: left;">Nachfrage</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><strong>250</strong></td>
<td style="text-align: left;"><span class="math inline">\(I^P\)</span> sinkt auf 0. <span class="math inline">\(I^D = 300 - 50 = 250\)</span>. <span class="math inline">\(I^D &gt; s\)</span>, keine neue Bestellung.</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>4</strong></td>
<td style="text-align: left;"><strong>Wareneingang</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><strong>250</strong></td>
<td style="text-align: left;">Die Bestellung aus Woche 1 (vor <span class="math inline">\(L=3\)</span> Wochen) trifft ein!</td>
</tr>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: left;">Nachfrage</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">205</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"><strong>205</strong></td>
<td style="text-align: left;"><span class="math inline">\(I^P\)</span> sinkt. <span class="math inline">\(I^D = 250 - 45 = 205\)</span>. <span class="math inline">\(I^D &gt; s\)</span>, keine neue Bestellung.</td>
</tr>
</tbody>
</table>
</section>
<section id="servicegrade" class="slide level2 scrollable">
<h2>3. Servicegrade</h2>
<h3 id="der-alpha-servicegrad-zyklus-servicegrad">Der <span class="math inline">\(\alpha\)</span>-Servicegrad (Zyklus-Servicegrad)</h3>
<blockquote>
<p><strong>Frage:</strong> “Wie hoch ist die Wahrscheinlichkeit, dass wir in einem Bestellzyklus <em>keinen</em> Fehlbestand haben?”</p>
</blockquote>
<p>Ein <span class="math inline">\(\alpha\)</span>-Servicegrad von 99% bedeutet, dass in 99 von 100 Bestellzyklen (die Zeit zwischen zwei Bestellungen) die Nachfrage vollständig aus dem Lager bedient werden kann. Er fokussiert auf das <em>Ereignis</em> eines Fehlbestands.</p>
<p>Formelhaft ausgedrückt ist der <span class="math inline">\(\alpha\)</span>-Servicegrad<sup>1</sup> die Wahrscheinlichkeit, dass die Nachfrage im Risikozeitraum (<span class="math inline">\(Y_L\)</span>) den Bestellpunkt (<span class="math inline">\(s\)</span>) nicht übersteigt: <span class="math display">\[
\alpha = P(Y_L \le s)
\]</span></p>
<h3 id="der-beta-servicegrad-mengen-servicegrad-oder-fill-rate">Der <span class="math inline">\(\beta\)</span>-Servicegrad (Mengen-Servicegrad oder “Fill Rate”)</h3>
<blockquote>
<p><strong>Frage:</strong> “Welchen prozentualen Anteil der gesamten Nachfrage können wir direkt aus dem Lager bedienen?”</p>
</blockquote>
<p>Ein <span class="math inline">\(\beta\)</span>-Servicegrad von 99% bedeutet, dass 99 von 100 nachgefragten Einheiten sofort geliefert werden können. Er fokussiert auf die <em>Menge</em> der nicht gelieferten Einheiten.</p>
<p>Er wird berechnet, indem man die erwartete Fehlmenge pro Zyklus (<span class="math inline">\(E(B)\)</span>) ins Verhältnis zur Bestellmenge (<span class="math inline">\(q\)</span>) setzt: <span class="math display">\[
\beta = 1 - \frac{E(B)}{q}
\]</span></p>
<h3 id="der-gamma-servicegrad-zeitbezogener-servicegrad">Der <span class="math inline">\(\gamma\)</span>-Servicegrad (Zeitbezogener Servicegrad)</h3>
<blockquote>
<p><strong>Frage:</strong> “Wie viel Prozent der Zeit ist unser Produkt tatsächlich auf Lager und verfügbar?”</p>
</blockquote>
<p>Dieser Servicegrad betrachtet das Problem aus einer zeitlichen Perspektive. Ein <span class="math inline">\(\gamma\)</span>-Servicegrad von 99% bedeutet, dass an 99 von 100 Tagen ein Kunde, der unseren Shop besucht, das Produkt in den Warenkorb legen könnte. Er fokussiert sich auf die <em>permanente Verfügbarkeit</em>.</p>
<p>Konzeptionell lässt er sich so darstellen: <span class="math display">\[
\gamma \approx \frac{\text{Zeit mit positivem Lagerbestand}}{\text{Gesamtzeit}}
\]</span> Die exakte Berechnung ist aufwändiger, aber das Ziel ist einfach die Minimierung der Zeitfenster, in denen Kunden ein leeres Regal vorfinden.</p>
<p><strong>Zusammenfassend:</strong></p>
<ul>
<li><strong><span class="math inline">\(\alpha\)</span></strong>: Vermeiden des <em>Ereignisses</em> “Fehlbestand”.</li>
<li><strong><span class="math inline">\(\beta\)</span></strong>: Minimieren der <em>Menge</em> nicht gelieferter Einheiten.</li>
<li><strong><span class="math inline">\(\gamma\)</span></strong>: Maximieren der <em>Zeitspanne</em> der Lieferfähigkeit.</li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn1"><p>Bei einer Normalverteilung entspricht dies genau dem Wert, den wir in der z-Tabelle suchen: <span class="math inline">\(\alpha = \Phi(z)\)</span>.</p></li></ol></aside></section>
<section id="die-nachfrage-im-risikozeitraum" class="slide level2">
<h2>4. Die Nachfrage im Risikozeitraum</h2>
<p>Der kritischste Moment für jedes Lager ist die <strong>Wiederbeschaffungszeit (WBZ)</strong>, auch <strong>Risikozeitraum</strong> genannt. Das ist die Zeitspanne <span class="math inline">\(L\)</span> zwischen dem Absenden einer Bestellung und dem Eintreffen der Ware. In dieser Zeit können wir nicht auf unvorhergesehen hohe Nachfrage reagieren – unser Lager ist auf sich allein gestellt.</p>
<p>Um unseren Bestellpunkt <span class="math inline">\(s\)</span> festzulegen, müssen wir die Nachfrage während dieses Risikozeitraums (<span class="math inline">\(Y_L\)</span>) modellieren.</p>
<h3 id="fall-1-nachfrage-ist-normalverteilt">Fall 1: Nachfrage ist normalverteilt</h3>
<p>Sehr oft kann die Summe vieler kleiner, zufälliger Nachfragen durch eine Normalverteilung (Glockenkurve) angenähert werden.</p>
<p>Angenommen, die wöchentliche Nachfrage hat einen Mittelwert <span class="math inline">\(\mu_d\)</span> und eine Standardabweichung <span class="math inline">\(\sigma_d\)</span>. Für eine WBZ von <span class="math inline">\(L\)</span> Wochen gilt dann für die Gesamtnachfrage <span class="math inline">\(Y_L\)</span>:</p>
<ul>
<li><strong>Erwartete Nachfrage während der WBZ:</strong> <span class="math inline">\(\mu_L = L \cdot \mu_d\)</span></li>
<li><strong>Standardabweichung der Nachfrage während der WBZ:</strong> <span class="math inline">\(\sigma_L = \sqrt{L} \cdot \sigma_d\)</span></li>
</ul>
<p><strong>Beispiel:</strong></p>
<ul>
<li>Wöchentliche Nachfrage <span class="math inline">\(\mu_d = 50\)</span>, <span class="math inline">\(\sigma_d = 15\)</span>.</li>
<li>WBZ <span class="math inline">\(L=4\)</span> Wochen.</li>
</ul>
<p>Daraus folgt:</p>
<ul>
<li><span class="math inline">\(\mu_L = 4 \cdot 50 = 200\)</span> Stück</li>
<li><span class="math inline">\(\sigma_L = \sqrt{4} \cdot 15 = 2 \cdot 15 = 30\)</span> Stück</li>
</ul>
<p>Wir erwarten also, in den 4 Wochen 200 Stück zu verkaufen, mit einer Unsicherheit von <span class="math inline">\(\sigma_L = 30\)</span>.</p>
<h3 id="fall-2-nachfrage-ist-diskret-faltung">Fall 2: Nachfrage ist diskret (Faltung)</h3>
<p>Manchmal ist die Nachfrage klein und diskret. Zum Beispiel verkauft ein Kiosk pro Tag 0, 1 oder 2 Flaschen einer speziellen Limonade. Wie ermittelt man die Nachfrageverteilung für eine WBZ von 2 Tagen? Wir müssen alle Möglichkeiten kombinieren. Diesen Prozess nennt man <strong>Faltung</strong>.</p>
<p><strong>Beispiel:</strong></p>
<ul>
<li>Tägliche Nachfrage <span class="math inline">\(D\)</span>: <span class="math inline">\(P(D=0)=0.2\)</span>, <span class="math inline">\(P(D=1)=0.6\)</span>, <span class="math inline">\(P(D=2)=0.2\)</span>.</li>
<li>WBZ <span class="math inline">\(L=2\)</span> Tage.</li>
</ul>
<p>Wir wollen die Verteilung für <span class="math inline">\(Y_2 = D_1 + D_2\)</span> finden, wobei <span class="math inline">\(D_1\)</span> die Nachfrage an Tag 1 und <span class="math inline">\(D_2\)</span> die an Tag 2 ist.</p>
<ul>
<li><strong><span class="math inline">\(P(Y_2 = 0)\)</span>:</strong> Geht nur mit (0, 0) <span class="math inline">\(\implies 0.2 \cdot 0.2 = 0.04\)</span></li>
<li><strong><span class="math inline">\(P(Y_2 = 1)\)</span>:</strong> Geht mit (0, 1) und (1, 0) <span class="math inline">\(\implies (0.2 \cdot 0.6) + (0.6 \cdot 0.2) = 0.24\)</span></li>
<li><strong><span class="math inline">\(P(Y_2 = 2)\)</span>:</strong> Geht mit (0, 2), (1, 1), (2, 0) <span class="math inline">\(\implies (0.2 \cdot 0.2) + (0.6 \cdot 0.6) + (0.2 \cdot 0.2) = 0.44\)</span></li>
<li><strong><span class="math inline">\(P(Y_2 = 3)\)</span>:</strong> Geht mit (1, 2) und (2, 1) <span class="math inline">\(\implies (0.6 \cdot 0.2) + (0.2 \cdot 0.6) = 0.24\)</span></li>
<li><strong><span class="math inline">\(P(Y_2 = 4)\)</span>:</strong> Geht nur mit (2, 2) <span class="math inline">\(\implies 0.2 \cdot 0.2 = 0.04\)</span></li>
</ul>
<p>Die Verteilung für die Gesamtnachfrage über 2 Tage ist also:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(Y_2\)</span></th>
<th style="text-align: left;">0</th>
<th style="text-align: left;">1</th>
<th style="text-align: left;">2</th>
<th style="text-align: left;">3</th>
<th style="text-align: left;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">P(<span class="math inline">\(Y_2\)</span>)</td>
<td style="text-align: left;">0.04</td>
<td style="text-align: left;">0.24</td>
<td style="text-align: left;">0.44</td>
<td style="text-align: left;">0.24</td>
<td style="text-align: left;">0.04</td>
</tr>
</tbody>
</table>
</section>
<section id="den-bestellpunkt-s-berechnen" class="slide level2 scrollable">
<h2>5. Den Bestellpunkt <span class="math inline">\(s\)</span> berechnen</h2>
<p>Der Bestellpunkt <span class="math inline">\(s\)</span> muss so hoch sein, dass er die Nachfrage während der Wiederbeschaffungszeit mit hoher Wahrscheinlichkeit decken kann. Er besteht aus zwei Teilen:</p>
<p><span class="math display">\[
s = (\text{Erwartete Nachfrage während WBZ}) + (\text{Sicherheitspuffer})
\]</span> <span class="math display">\[
s = \mu_L + \text{Sicherheitsbestand (SS)}
\]</span></p>
<p>Der <strong>Sicherheitsbestand (SS)</strong> ist der zusätzliche Vorrat, den wir nur für den Fall halten, dass die Nachfrage höher als erwartet ausfällt. Seine Höhe hängt direkt von unserem gewünschten Servicegrad ab.</p>
<h3 id="sicherheitsbestand-bei-normalverteilung">Sicherheitsbestand bei Normalverteilung</h3>
<p>Bei normalverteilter Nachfrage lässt sich der Bestellpunkt direkt mit einer Formel berechnen, die den Sicherheitsbestand bereits enthält:</p>
<p><span class="math display">\[
s = \mu_L + z \cdot \sigma_L
\]</span></p>
<p>Hierbei ist:</p>
<ul>
<li><span class="math inline">\(\mu_L\)</span> der Erwartungswert und <span class="math inline">\(\sigma_L\)</span> die Standardabweichung der Nachfrage während der WBZ.</li>
<li><strong>z</strong> ist der <strong>Sicherheitsfaktor</strong>. Er ist ein Wert aus der Standardnormalverteilung, der direkt von unserem gewünschten <span class="math inline">\(\alpha\)</span>-Servicegrad abhängt.</li>
<li>Der Teil <span class="math inline">\(z \cdot \sigma_L\)</span> ist der <strong>Sicherheitsbestand (SS)</strong>.</li>
</ul>
<p>Je höher der Servicegrad, desto größer der z-Wert und desto mehr Sicherheitsbestand halten wir. <sup>1</sup></p>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 11%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(\alpha\)</span>-Servicegrad</th>
<th style="text-align: center;">z-Wert</th>
<th style="text-align: left;">Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">50%</td>
<td style="text-align: center;">0.000</td>
<td style="text-align: left;">Exakt der Erwartungswert (kein Puffer).</td>
</tr>
<tr class="even">
<td style="text-align: left;">55%</td>
<td style="text-align: center;">0.126</td>
<td style="text-align: left;">0.126 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">60%</td>
<td style="text-align: center;">0.253</td>
<td style="text-align: left;">0.253 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">65%</td>
<td style="text-align: center;">0.385</td>
<td style="text-align: left;">0.385 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">70%</td>
<td style="text-align: center;">0.524</td>
<td style="text-align: left;">0.524 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">75%</td>
<td style="text-align: center;">0.674</td>
<td style="text-align: left;">0.674 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80%</td>
<td style="text-align: center;">0.842</td>
<td style="text-align: left;">0.842 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">85%</td>
<td style="text-align: center;">1.036</td>
<td style="text-align: left;">1.036 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">90%</td>
<td style="text-align: center;">1.282</td>
<td style="text-align: left;">1.282 Standardabweichungen als Puffer.</td>
</tr>
<tr class="even">
<td style="text-align: left;">95%</td>
<td style="text-align: center;">1.645</td>
<td style="text-align: left;">1.645 Standardabweichungen als Puffer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">99%</td>
<td style="text-align: center;">2.326</td>
<td style="text-align: left;">2.326 Standardabweichungen als Puffer.</td>
</tr>
</tbody>
</table>
<p><strong>Beispiel (Fortsetzung von Fall 1):</strong></p>
<ul>
<li><span class="math inline">\(\mu_L = 200\)</span>, <span class="math inline">\(\sigma_L = 30\)</span>.</li>
<li>Wir streben einen <span class="math inline">\(\alpha\)</span>-Servicegrad von 99% an.</li>
</ul>
<ol type="1">
<li><strong>z-Wert finden:</strong> Für <span class="math inline">\(\alpha=99\%\)</span> ist <span class="math inline">\(z \approx 2.326\)</span>.</li>
<li><strong>Sicherheitsbestand berechnen:</strong> <span class="math inline">\(SS = 2.326 \cdot 30 \approx 69.78 \approx 70\)</span> Stück.</li>
<li><strong>Bestellpunkt berechnen:</strong> <span class="math inline">\(s = \mu_L + SS = 200 + 70 = 270\)</span> Stück.</li>
</ol>
<p>Wir würden also immer dann eine neue Bestellung auslösen, wenn unser verfügbarer Bestand auf 270 Stück sinkt.</p>
<aside><ol class="aside-footnotes"><li id="fn2"><p>Den z-Wert finden wir in einer z-Tabelle oder berechnen ihn mit einer Funktion wie <code>NORM.S.INV()</code> in Excel oder <code>norm.ppf()</code> in Python.</p></li></ol></aside></section>
<section id="wie-groß-ist-die-fehlmenge" class="slide level2 scrollable">
<h2>6. Wie groß ist die Fehlmenge?</h2>
<p>Wir wissen nun, <em>wie wahrscheinlich</em> ein Fehlbestand ist (<span class="math inline">\(\alpha\)</span>-Servicegrad).</p>
<ul>
<li>Aber <em>wie viele Einheiten fehlen uns im Durchschnitt</em>, wenn es zu einem Fehlbestand kommt?</li>
<li>Das ist die <strong>erwartete Fehlmenge pro Zyklus</strong>, <span class="math inline">\(E(B)\)</span>.</li>
</ul>
<h3 id="erwartete-fehlmenge-bei-normalverteilung">Erwartete Fehlmenge bei Normalverteilung</h3>
<p>Hier können wir die sogenannte <strong>Einheiten-Verlustfunktion</strong> <span class="math inline">\(G_u(z)\)</span> verwenden:</p>
<p><span class="math display">\[
E(B) = \sigma_L \cdot G_u(z)
\]</span></p>
<p>Der Wert für <span class="math inline">\(G_u(z)\)</span> hängt nur vom Sicherheitsfaktor <span class="math inline">\(z\)</span> ab. <sup>1</sup></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">z-Wert</th>
<th style="text-align: left;"><span class="math inline">\(G_u(z)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1.282</td>
<td style="text-align: left;">0.047</td>
</tr>
<tr class="even">
<td style="text-align: left;">1.645</td>
<td style="text-align: left;">0.021</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2.326</td>
<td style="text-align: left;">0.003</td>
</tr>
</tbody>
</table>
<p><strong>Beispiel (Fortsetzung von Fall 1):</strong> <span class="math inline">\(z=2.326\)</span>, <span class="math inline">\(\sigma_L=30\)</span>.</p>
<ul>
<li><span class="math inline">\(E(B) = 30 \cdot G_u(2.326) = 30 \cdot 0.003 = 0.09\)</span> Stück.</li>
<li>Da unser Servicegrad hier sehr hoch ist, erwarten wir im Durchschnitt (über viele Zyklen) nur eine kleine Fehlmenge von 0.09 Stück pro Zyklus.</li>
</ul>
<h3 id="erwartete-fehlmenge-bei-diskreter-verteilung">Erwartete Fehlmenge bei diskreter Verteilung</h3>
<p>Hier berechnen wir den Erwartungswert direkt, indem wir alle möglichen Fehlmengen mit ihrer Wahrscheinlichkeit gewichten:</p>
<p><span class="math display">\[
E(B) = \sum_{\text{alle } y} \max(0, y - s) \cdot P(Y_L=y)
\]</span></p>
<p><strong>Beispiel (Limonaden-Kiosk, unser Beispiel aus Fall 2):</strong></p>
<ul>
<li>Bestellpunkt <span class="math inline">\(s=3\)</span>.</li>
<li>Die Nachfrageverteilung <span class="math inline">\(P(Y_2)\)</span> kennen wir von oben.</li>
</ul>
<p>Das bedeutet, dass wir im Durchschnitt 0.04 Flaschen pro Zyklus verlieren.</p>
<ul>
<li>Eine Fehlmenge tritt nur auf, wenn die Nachfrage <span class="math inline">\(Y_2 &gt; 3\)</span> ist. Das ist nur bei <span class="math inline">\(Y_2=4\)</span> der Fall.</li>
<li>Fehlmenge bei <span class="math inline">\(Y_2=4\)</span> ist <span class="math inline">\(4 - s = 4 - 3 = 1\)</span> Flasche. <sup>2</sup></li>
<li><span class="math inline">\(P(Y_2=4) = 0.04\)</span>.</li>
<li><span class="math inline">\(E(B) = (1 \text{ Flasche}) \cdot 0.04 = 0.04\)</span> Flaschen.</li>
</ul>
<h3 id="den-beta-servicegrad-berechnen">Den <span class="math inline">\(\beta\)</span>-Servicegrad berechnen</h3>
<p>Mit unserem berechneten Wert für die erwartete Fehlmenge <span class="math inline">\(E(B)\)</span> und der in Abschnitt 3 vorgestellten Formel können wir nun den <span class="math inline">\(\beta\)</span>-Servicegrad (Fill Rate) für eine gegebene Bestellmenge <span class="math inline">\(q\)</span> ausrechnen.</p>
<p><strong>Beispiel (Smartphone):</strong> Wir haben <span class="math inline">\(E(B)=0.09\)</span> berechnet, die feste Bestellmenge sei <span class="math inline">\(q=500\)</span>.</p>
<p><span class="math inline">\(\beta = 1 - \frac{E(B)}{q} = 1 - \frac{0.09}{500} = 1 - 0.00018 = 0.99982\)</span></p>
<ul>
<li>Der <span class="math inline">\(\beta\)</span>-Servicegrad ist 99.982%.</li>
<li>Das ist extrem hoch und zeigt, dass bei einer so großen Bestellmenge die wenigen erwarteten Fehlmengen kaum ins Gewicht fallen.</li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn3"><p>Der Wert für <span class="math inline">\(G_u(z)\)</span> kann aus Tabellen abgelesen oder berechnet werden (<span class="math inline">\(\phi(z) - z(1 - \Phi(z))\)</span>).</p></li><li id="fn4"><p>Wir haben hier die Nachfrageverteilung <span class="math inline">\(P(Y_2)\)</span> verwendet, um die Wahrscheinlichkeit für eine Fehlmenge zu berechnen.</p></li></ol></aside></section>
<section id="erweiterte-service-perspektiven" class="slide level2 scrollable">
<h2>7. Erweiterte Service-Perspektiven</h2>
<p>Manchmal ist es nicht nur wichtig, <em>ob</em> ein Fehlbestand auftritt, sondern auch, <em>wen</em> er betrifft.</p>
<h3 id="kundenpriorisierung">Kundenpriorisierung</h3>
<p>Stellen wir uns vor, wir beliefern nicht nur Privatkunden, sondern auch ein Luxus-Café, das ein wichtiger Stammkunde ist. Ein Fehlbestand bei diesem Kunden wäre weitaus schlimmer als bei einem einmaligen Online-Besteller. Hier kann man über <strong>Kundenklassen</strong> nachdenken.</p>
<p>Man kann den Bestand so steuern, dass wichtige Kunden bevorzugt behandelt werden. Zwei einfache Strategien sind:</p>
<ol type="1">
<li><strong>Getrennte Bestände:</strong> Wir halten einen kleinen, separaten “Notfall-Bestand” nur für das Café. Das ist sicher, aber ineffizient, weil dieser Bestand die meiste Zeit nur herumliegt.</li>
<li><strong>Rationierung:</strong> Eine intelligentere Methode. Wir haben einen gemeinsamen Bestand. Fällt dieser aber unter ein kritisches Niveau (z.B. 20 Stück), werden ab diesem Moment nur noch Bestellungen vom Luxus-Café angenommen. Alle anderen Kunden müssen warten. So schützt man seine wichtigsten Partner, ohne permanent Ware blockieren zu müssen.</li>
</ol>
<h3 id="die-kundenwartezeit-reichweite-und-lieferunfähigkeit">Die Kundenwartezeit: Reichweite und Lieferunfähigkeit</h3>
<p>Neben den Servicegraden können wir auch fragen: Was bedeutet ein bestimmter Sicherheitsbestand für die Wartezeit der Kunden?</p>
<ul>
<li><p><strong>Reichweite:</strong> Stellt die Frage: “Wie viele Perioden (z.B. Wochen) reicht unser Lagerbestand noch, ab dem Moment, in dem wir nachbestellen?” Eine einfache Näherungsformel für die <em>erwartete Reichweite</em> lautet: <span class="math display">\[
\text{Erwartete Reichweite} \approx \frac{s}{\mu_d}
\]</span> wobei <span class="math inline">\(s\)</span> der Bestellpunkt und <span class="math inline">\(\mu_d\)</span> die durchschnittliche Nachfrage <em>pro Periode</em> ist. Bei einem Bestellpunkt von <span class="math inline">\(s=270\)</span> und einer wöchentlichen Nachfrage von <span class="math inline">\(\mu_d=50\)</span> wäre die erwartete Reichweite also <span class="math inline">\(270 / 50 = 5.4\)</span> Wochen. <sup>1</sup></p></li>
<li><p><strong>Lieferunfähigkeitsdauer:</strong> Dies ist die durchschnittliche Zeit, in der wir <em>keine Ware</em> haben. Eine Lieferunfähigkeit entsteht, wenn die Wiederbeschaffungszeit länger ist als die Reichweite des Bestands. <span class="math display">\[
\text{Erwartete Lieferunfähigkeitsdauer} \approx \max(0, L - \text{Erwartete Reichweite})
\]</span> wobei <span class="math inline">\(L\)</span> die Wiederbeschaffungszeit ist. Nehmen wir an, wir würden einen niedrigeren Servicegrad von 85% anstreben (<span class="math inline">\(\alpha=0.85\)</span>, <span class="math inline">\(z=1.036\)</span>). Der neue Bestellpunkt wäre <span class="math inline">\(s = 200 + 1.036 \cdot 30 \approx 231\)</span>. Die erwartete Reichweite wäre dann <span class="math inline">\(231 / 50 \approx 4.62\)</span> Wochen. Mit einer Wiederbeschaffungszeit von <span class="math inline">\(L=4\)</span> Wochen ergibt sich:</p>
<p><span class="math display">\[
\text{Erwartete Lieferunfähigkeitsdauer} \approx \max(0, 4 - 4.62) = 0
\]</span></p>
<p>Selbst bei einem 85%-Servicegrad erwarten wir nach dieser Näherung keine Lieferunfähigkeit. Würde unsere Wiederbeschaffungszeit jedoch auf <span class="math inline">\(L=5\)</span> Wochen steigen, wäre die Situation anders:</p>
<p><span class="math display">\[
\text{Erwartete Lieferunfähigkeitsdauer} \approx \max(0, 5 - 4.62) = 0.38 \text{ Wochen}
\]</span></p>
<p>Wir müssten also mit einer durchschnittlichen Lieferunfähigkeit von fast einer halben Woche rechnen. <sup>2</sup></p></li>
</ul>
<p>Beide Kennzahlen hängen direkt von unserem Sicherheitsbestand ab. Ein höherer Sicherheitsbestand (und damit ein höherer Bestellpunkt <span class="math inline">\(s\)</span>) erhöht die Reichweite und senkt die Dauer der Lieferunfähigkeit. Diese Kennzahlen helfen uns, die Auswirkungen unserer Bestandsentscheidungen direkt in “Kundenwartezeit” zu übersetzen.</p>


<aside><ol class="aside-footnotes"><li id="fn5"><p>Dies ist eine <strong>Näherung</strong>, weil die tatsächliche Reichweite von der zufälligen Abfolge der Nachfragen abhängt. Die Formel gibt uns aber einen sehr guten und schnellen Schätzwert.</p></li><li id="fn6"><p>Diese Formel ist ebenfalls eine <strong>Näherung</strong>, da sie auf der angenäherten Reichweite basiert.</p></li></ol></aside></section>

    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Vorlesung 04: Bestandsmanagement | Tobias Vlćek | <a href="../part-04/mlb-lecture-04_new.html">Home</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1200,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/beyondsimulations\.github\.io\/Materiallogistik");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>